export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const POLL_LIST_REQUEST = "POLL_LIST_REQUEST";
export const POLL_LIST_SUCCESS = "POLL_LIST_SUCCESS";
export const POLL_LIST_ERROR = "POLL_LIST_ERROR";

export const DELETE_POLL_REQUEST = "DELETE_POLL_REQUEST";
export const DELETE_POLL_SUCCESS = "DELETE_POLL_SUCCESS";
export const DELETE_POLL_ERROR = "DELETE_POLL_ERROR";

export const CREATE_NEWPOLL_REQUEST = "CREATE_NEWPOLL_REQUEST";
export const CREATE_NEWPOLL_SUCCESS = "CREATE_NEWPOLL_SUCCESS";
export const CREATE_NEWPOLL_ERROR = "CREATE_NEWPOLL_ERROR";

export const UPDATE_POLLTITLE_REQUEST = "UPDATE_POLLTITLE_REQUEST";
export const UPDATE_POLLTITLE_SUCCESS = "UPDATE_POLLTITLE_SUCCESS";
export const UPDATE_POLLTITLE_ERROR= "UPDATE_POLLTITLE_ERROR";

export const ADDNEW_OPTIONREQUEST = "ADDNEW_OPTIONREQUEST";
export const ADDNEW_OPTIONSUCCESS = "ADDNEW_OPTIONSUCCESS";
export const ADDNEW_OPTIONERROR = "ADDNEW_OPTIONERROR";

export const DELETE_OPTION_REQUEST = "DELETE_OPTION_REQUEST";
export const DELETE_OPTION_SUCCESS = "DELETE_OPTION_SUCCESS";
export const DELETE_OPTION_ERROR = "DELETE_OPTION_ERROR";

export const POLL_REQUEST = "POLL_REQUEST";
export const POLL_SUCCESS = "POLL_SUCCESS";
export const POLL_ERROR = "POLL_ERROR";